# Copyright (c) Sudeep Dasari, 2023

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.


_target_: factr.task.BCTask
obs_dim: 7
ac_dim: 7
cam_indexes: [0]
n_cams: ${len:${task.cam_indexes}}


train_buffer:
  _target_: factr.replay_buffer.RobobufReplayBuffer
  buffer_path: ${buffer_path}
  transform: ${transform:${train_transform}}
  n_test_ratio: 0.05
  ac_chunk: ${ac_chunk}
  mode: train
  cam_indexes: ${task.cam_indexes}
  past_frames: ${add:${img_chunk},-1}
  ac_dim: ${task.ac_dim}

test_buffer:
  _target_: factr.replay_buffer.RobobufReplayBuffer
  buffer_path: ${buffer_path}
  transform: ${transform:preproc}
  n_test_ratio: 0.05
  ac_chunk: ${ac_chunk}
  mode: test
  cam_indexes: ${task.cam_indexes}
  past_frames: ${add:${img_chunk},-1}
  ac_dim: ${task.ac_dim}
